services:
  mongo:
    image: mongo:7.0
    container_name: dev-mongo
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - dev_mongo_data:/data/db

volumes:
  dev_mongo_data:
