/**
 * The stamps a cook is logged with: what they are called, what colour they are
 * drawn in, and how an event that carries one is read back.
 *
 * Pure and dependency-free on purpose. A stamp is an identity (`key`) with a
 * display label hanging off it, and both the backend that records an event and
 * every client that draws one have to agree about that identity — so the
 * agreement lives in one module with no persistence, no Nest and no DTOs in it.
 *
 * This slice ships the defaults alone; the editable catalogue stored on the
 * application settings document arrives later, and arrives *here*, which is why
 * every resolver already takes the catalogue it resolves against.
 */

/**
 * The colours a stamp may be drawn in — named for what each one already means
 * on the chart (the chamber's line, the three probes) plus two the chart does
 * not use, so a stamp can stand apart from every reading on screen.
 */
export const STAMP_TONES = [
  'chamber',
  'p1',
  'p2',
  'p3',
  'amber',
  'sub',
] as const;

export type StampTone = (typeof STAMP_TONES)[number];

/** One entry of the catalogue. */
export interface CookStamp {
  /**
   * The stamp's stable identity. Events are keyed by it and never by the
   * label, so renaming a stamp renames its history rather than orphaning it.
   */
  key: string;
  /** What the button and the log row say. Display only. */
  label: string;
  tone: StampTone;
  /** Whether the stamp is offered. A disabled stamp keeps its history. */
  enabled: boolean;
  /** Whether the user added it — a default may be disabled but never removed. */
  custom: boolean;
}

/**
 * The stamp that says the meat has been wrapped.
 *
 * Named rather than spelled out where it is looked for, because it is asked
 * about outside the cook log: the Serve Plan drops its wrap hint once one of
 * these is stamped, and a second copy of the string would leave the hint on
 * forever the day the catalogue's key changed.
 */
export const WRAP_STAMP_KEY = 'wrap';

/**
 * The six stamps a pitmaster who has configured nothing gets, in the order the
 * buttons are laid out. Frozen: the exported defaults are the one copy of this
 * decision, and a caller that edited them in place would change what every
 * later reader sees.
 */
const DEFAULTS: readonly CookStamp[] = Object.freeze([
  {
    key: 'wood',
    label: 'Added Wood',
    tone: 'amber',
    enabled: true,
    custom: false,
  },
  {
    key: WRAP_STAMP_KEY,
    label: 'Wrapped',
    tone: 'p1',
    enabled: true,
    custom: false,
  },
  {
    key: 'spritz',
    label: 'Spritzed',
    tone: 'p2',
    enabled: true,
    custom: false,
  },
  { key: 'vent', label: 'Vent', tone: 'chamber', enabled: true, custom: false },
  { key: 'lid', label: 'Lid Open', tone: 'sub', enabled: true, custom: false },
  { key: 'sauce', label: 'Sauced', tone: 'p3', enabled: true, custom: false },
]);

/** The keys of the six defaults, in catalogue order. */
export const DEFAULT_STAMP_KEYS: readonly string[] = DEFAULTS.map(
  (stamp) => stamp.key,
);

/** A fresh, editable copy of the default catalogue. */
export const defaultStamps = (): CookStamp[] =>
  DEFAULTS.map((stamp) => ({ ...stamp }));

/** The catalogue entry for a key, or `undefined` when nothing carries it. */
export const findStamp = (
  key: string,
  catalogue: readonly CookStamp[] = DEFAULTS,
): CookStamp | undefined => catalogue.find((stamp) => stamp.key === key);

/**
 * What an event logged under `key` is called now.
 *
 * The catalogue wins over the snapshot, so a rename applies to everything ever
 * logged under that stamp; the snapshot is what keeps a since-removed custom
 * stamp's history legible rather than blank.
 */
export const resolveLabel = (
  key: string,
  snapshot: string,
  catalogue: readonly CookStamp[] = DEFAULTS,
): string => findStamp(key, catalogue)?.label ?? snapshot;

/** The colour an event logged under `key` is drawn in, resolved the same way. */
export const resolveTone = (
  key: string,
  snapshot: StampTone,
  catalogue: readonly CookStamp[] = DEFAULTS,
): StampTone => findStamp(key, catalogue)?.tone ?? snapshot;

/**
 * The most stamps a catalogue may hold.
 *
 * Twelve is twice the shipped set: enough for anybody's real vocabulary, and
 * few enough that the touchscreen's scrolling row and the phone's three-column
 * grid stay something a gloved thumb can aim at.
 */
export const MAX_STAMPS = 12;

/** The longest a label may be — a button's width, not a sentence. */
export const MAX_STAMP_LABEL = 16;

/**
 * What a user-added stamp's key looks like: `custom-` and a ULID.
 *
 * Generated by whichever client added it, because the key has to exist before
 * the list it belongs to is posted. A ULID rather than a counter, so two
 * clients adding a stamp at once cannot mint the same identity and silently
 * merge two different stamps' histories.
 */
const CUSTOM_KEY = /^custom-[0-9ABCDEFGHJKMNPQRSTVWXYZ]{26}$/i;

/** Whether `key` is a well-formed user-added stamp's key. */
export const isCustomStampKey = (key: string): boolean => CUSTOM_KEY.test(key);

/** A stamp read off a document or a request: anything, until it is checked. */
type UnknownStamp = Partial<CookStamp> | null | undefined;

/**
 * A stored catalogue read as one this application can render.
 *
 * Tolerant, unlike {@link validateStamps}, because it is the read path: a
 * document written before the block existed, one whose defaults were dropped by
 * an older client, and one carrying a half-written entry all have to come back
 * as a usable set of buttons rather than as an error on the settings page. What
 * a client is *allowed to write* is a separate, strict question.
 *
 * Missing defaults are appended rather than inserted, so the order the user
 * chose for everything else survives.
 */
export const normalizeStamps = (
  stored: readonly UnknownStamp[] | null | undefined,
): CookStamp[] => {
  const seen = new Set<string>();
  const kept: CookStamp[] = [];
  (stored ?? []).forEach((entry) => {
    const key = typeof entry?.key === 'string' ? entry.key.trim() : '';
    const isDefault = DEFAULT_STAMP_KEYS.includes(key);
    if (!key || seen.has(key) || (!isDefault && !isCustomStampKey(key))) {
      return;
    }
    const label =
      typeof entry?.label === 'string'
        ? entry.label.trim().slice(0, MAX_STAMP_LABEL)
        : '';
    const fallback = findStamp(key);
    if (!label && !fallback) {
      return;
    }
    seen.add(key);
    kept.push({
      key,
      label: label || (fallback as CookStamp).label,
      tone: isTone(entry?.tone) ? entry.tone : (fallback?.tone ?? 'sub'),
      enabled: entry?.enabled !== false,
      custom: !isDefault,
    });
  });
  defaultStamps().forEach((stamp) => {
    if (!seen.has(stamp.key)) {
      kept.push(stamp);
    }
  });
  return kept.slice(0, MAX_STAMPS);
};

/** Whether a stored value names one of the colours a stamp may be drawn in. */
const isTone = (tone: unknown): tone is StampTone =>
  STAMP_TONES.includes(tone as StampTone);

/**
 * Why a catalogue a client asked to store may not be stored, or `null` when it
 * may.
 *
 * A reason rather than a boolean: this document is edited by a page the user is
 * looking at, and "rejected" with nothing said is a save that silently does not
 * happen. Strict where {@link normalizeStamps} is tolerant — the read path has
 * to render whatever is there, but a write is a client's claim about what the
 * catalogue should become, and every rule below is one a correct client keeps.
 *
 * The defaults may be disabled but never removed: an event keyed to one that
 * had been deleted would fall back to its snapshot forever, and the six are
 * what the touchscreen offers on an installation nobody has configured.
 */
export const validateStamps = (stamps: readonly CookStamp[]): string | null => {
  if (!Array.isArray(stamps)) {
    return 'Cook log stamps must be a list';
  }
  if (stamps.length > MAX_STAMPS) {
    return `A cook log may offer at most ${MAX_STAMPS} stamps`;
  }
  const seen = new Set<string>();
  for (const stamp of stamps) {
    const key = stamp?.key;
    if (typeof key !== 'string' || key.length === 0) {
      return 'Every stamp needs a key';
    }
    if (seen.has(key)) {
      return `Stamp keys must be unique: ${key} appears twice`;
    }
    seen.add(key);
    if (!DEFAULT_STAMP_KEYS.includes(key) && !isCustomStampKey(key)) {
      return `Stamp key ${key} is neither a default nor custom-<ulid>`;
    }
    const label = typeof stamp.label === 'string' ? stamp.label.trim() : '';
    if (label.length < 1 || label.length > MAX_STAMP_LABEL) {
      return `Stamp ${key} needs a label of 1 to ${MAX_STAMP_LABEL} characters`;
    }
    if (!isTone(stamp.tone)) {
      return `Stamp ${key} has an unknown tone: ${String(stamp.tone)}`;
    }
  }
  const dropped = DEFAULT_STAMP_KEYS.filter((key) => !seen.has(key));
  if (dropped.length > 0) {
    return `A default stamp may be disabled but not removed: ${dropped.join(
      ', ',
    )}`;
  }
  return null;
};

/**
 * The catalogue a Reset restores: the six defaults, enabled, and no customs.
 *
 * Named rather than left as a call to {@link defaultStamps} at the call site,
 * because "reset" is a decision about what a user gets back — the same list a
 * fresh installation has, not merely the list this module happens to seed with.
 */
export const resetStamps = (): CookStamp[] => defaultStamps();
