import { app, BrowserWindow } from 'electron';
import { resolveRendererUrl } from '../src/electron/rendererUrl';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// if (require('electron-squirrel-startup')) {
//   app.quit();
// }

const createWindow = (): void => {
  // Where the shell points: the launcher's override when it set one, otherwise
  // the URL shipping devices have always loaded.
  const rendererUrl = resolveRendererUrl(process.env);

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 480,
    width: 800,
    frame: false,
    fullscreen: true,
    // The window exists before there is a page in it, and it is reloaded into
    // whenever a load fails, so it opens in the colour the page it loads is
    // painted — otherwise the kiosk shows a white 800x480 panel for as long as
    // the load takes, which on a smoker whose wifi has dropped is every retry
    // below. Named here rather than taken from the shared theme: this is the
    // Electron main process, built without the renderer's packages. Guarded
    // against the shared token by src/electron/main.test.ts.
    backgroundColor: '#0C0C0C',
    webPreferences: {
      sandbox: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.setKiosk(true);

  mainWindow.loadURL(rendererUrl);

  mainWindow.webContents.on('did-fail-load', () => {
    mainWindow.loadURL(rendererUrl);
  })

  // mainWindow.webContents.openDevTools();

  // and load the index.html of the app.
  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.