#!/usr/bin/env bash
# Tests for scripts/verify-pr/inject-screenshots.sh
#
# Run: bash scripts/verify-pr/inject-screenshots.test.sh
#
# Pure text transform over a human-visible artifact (the PR description), run
# once per verification round on the SAME PR. The two failure modes that matter
# are (a) accumulating stale image walls round after round and (b) clobbering
# text a human wrote — both are asserted here.
#
# Rules under test:
#   - the section is inserted before the verification checklist
#   - a second run REPLACES the generated section (idempotent, no growth)
#   - captions and URLs render as markdown images, in input order
#   - empty stdin leaves the body byte-identical
#   - a `## Screenshots` heading a human wrote (no marker) is left alone
#   - bodies with no checklist fall back to the footer rule, then to append
#   - the rest of the body survives verbatim

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INJECT="${SCRIPT_DIR}/inject-screenshots.sh"

TESTS_RUN=0
TESTS_FAILED=0
FAILED_NAMES=()

pass() {
    TESTS_RUN=$((TESTS_RUN + 1))
    echo "  PASS: $1"
}

fail() {
    TESTS_RUN=$((TESTS_RUN + 1))
    TESTS_FAILED=$((TESTS_FAILED + 1))
    FAILED_NAMES+=("$1")
    echo "  FAIL: $1"
    if [ -n "${2:-}" ]; then
        echo "    $2"
    fi
}

if [ ! -f "${INJECT}" ]; then
    echo "FATAL: ${INJECT} not found"
    exit 2
fi

SHOTS_ONE=$'Settings page\thttps://github.com/user-attachments/assets/aaa111'
SHOTS_TWO=$'Settings page\thttps://github.com/user-attachments/assets/aaa111\nSmoke screen (smoker)\thttps://github.com/user-attachments/assets/bbb222'

# A realistic team-pickup PR body.
write_body() {
    cat > "$1" <<'EOF'
## Summary

Restyle the settings shell with the Carbon light theme.

## Closes

Closes #419 — settings restyle

## Smoke

`smoke: PASS`

## Manual verification

- [ ] Settings page renders the Carbon light palette
- [x] Toggle persists across reload

---

Generated by `/team-pickup` at 2026-08-02T10:00:00Z
EOF
}

#-------------------------------------------------------------------------------
# Test 1: inserted before the checklist, images rendered in input order.
#-------------------------------------------------------------------------------
test_inserts_before_checklist() {
    echo "TEST: section lands before the checklist, images in input order"

    local body out
    body="$(mktemp)"
    trap "rm -f '${body}'" RETURN
    write_body "${body}"

    out="$(printf '%s\n' "${SHOTS_TWO}" | bash "${INJECT}" "${body}")"

    local shot_line checklist_line
    shot_line="$(printf '%s\n' "${out}" | grep -n '^## Screenshots$' | cut -d: -f1)"
    checklist_line="$(printf '%s\n' "${out}" | grep -n '^## Manual verification$' | cut -d: -f1)"

    if [ -n "${shot_line}" ] && [ -n "${checklist_line}" ] && [ "${shot_line}" -lt "${checklist_line}" ]; then
        pass "## Screenshots precedes ## Manual verification"
    else
        fail "## Screenshots precedes ## Manual verification" "shot=${shot_line} checklist=${checklist_line}"
    fi

    if printf '%s\n' "${out}" | grep -qF '![Settings page](https://github.com/user-attachments/assets/aaa111)' &&
        printf '%s\n' "${out}" | grep -qF '![Smoke screen (smoker)](https://github.com/user-attachments/assets/bbb222)'; then
        pass "both images render as markdown"
    else
        fail "both images render as markdown" "${out}"
    fi

    local first second
    first="$(printf '%s\n' "${out}" | grep -n 'aaa111' | head -1 | cut -d: -f1)"
    second="$(printf '%s\n' "${out}" | grep -n 'bbb222' | head -1 | cut -d: -f1)"
    if [ "${first}" -lt "${second}" ]; then
        pass "images keep input order"
    else
        fail "images keep input order" "first=${first} second=${second}"
    fi

    if printf '%s\n' "${out}" | grep -qF '<!-- verify-pr-screenshots -->'; then
        pass "section carries the ownership marker"
    else
        fail "section carries the ownership marker"
    fi
}

#-------------------------------------------------------------------------------
# Test 2: idempotence — a re-verify round replaces, never accumulates.
#-------------------------------------------------------------------------------
test_idempotent_replace() {
    echo "TEST: a second round replaces the generated section"

    local body round1 round2 round3
    body="$(mktemp)"
    trap "rm -f '${body}'" RETURN
    write_body "${body}"

    round1="$(printf '%s\n' "${SHOTS_TWO}" | bash "${INJECT}" "${body}")"
    printf '%s\n' "${round1}" > "${body}"
    round2="$(printf '%s\n' "${SHOTS_TWO}" | bash "${INJECT}" "${body}")"

    if [ "${round1}" = "${round2}" ]; then
        pass "same input twice is a fixed point"
    else
        fail "same input twice is a fixed point" "$(diff <(printf '%s\n' "${round1}") <(printf '%s\n' "${round2}") | head -20)"
    fi

    local headings
    headings="$(printf '%s\n' "${round2}" | grep -c '^## Screenshots$')"
    if [ "${headings}" -eq 1 ]; then
        pass "exactly one ## Screenshots heading after two rounds"
    else
        fail "exactly one ## Screenshots heading after two rounds" "count=${headings}"
    fi

    printf '%s\n' "${round2}" > "${body}"
    round3="$(printf '%s\n' "${SHOTS_ONE}" | bash "${INJECT}" "${body}")"
    if printf '%s\n' "${round3}" | grep -qF 'aaa111' && ! printf '%s\n' "${round3}" | grep -qF 'bbb222'; then
        pass "a shorter round drops the stale image"
    else
        fail "a shorter round drops the stale image" "${round3}"
    fi
}

#-------------------------------------------------------------------------------
# Test 3: empty stdin never mutates.
#-------------------------------------------------------------------------------
test_empty_input_is_noop() {
    echo "TEST: empty stdin leaves the body byte-identical"

    local body out
    body="$(mktemp)"
    trap "rm -f '${body}'" RETURN
    write_body "${body}"

    out="$(printf '' | bash "${INJECT}" "${body}")"
    if [ "${out}" = "$(cat "${body}")" ]; then
        pass "no shots → body unchanged"
    else
        fail "no shots → body unchanged" "$(diff <(cat "${body}") <(printf '%s\n' "${out}") | head)"
    fi

    # And a body that already carries a section keeps it.
    local with out2
    with="$(printf '%s\n' "${SHOTS_ONE}" | bash "${INJECT}" "${body}")"
    printf '%s\n' "${with}" > "${body}"
    out2="$(printf '' | bash "${INJECT}" "${body}")"
    if printf '%s\n' "${out2}" | grep -qF 'aaa111'; then
        pass "an empty round preserves an earlier round's images"
    else
        fail "an empty round preserves an earlier round's images"
    fi
}

#-------------------------------------------------------------------------------
# Test 4: a human's own ## Screenshots section (no marker) is not touched.
#-------------------------------------------------------------------------------
test_human_section_untouched() {
    echo "TEST: an unmarked ## Screenshots section a human wrote survives"

    local body out
    body="$(mktemp)"
    trap "rm -f '${body}'" RETURN
    cat > "${body}" <<'EOF'
## Summary

Restyle.

## Screenshots

Here is the mock I worked from: https://example.com/mock.png

## Manual verification

- [ ] Settings page renders
EOF

    out="$(printf '%s\n' "${SHOTS_ONE}" | bash "${INJECT}" "${body}")"

    if printf '%s\n' "${out}" | grep -qF 'Here is the mock I worked from'; then
        pass "human prose preserved"
    else
        fail "human prose preserved" "${out}"
    fi
    if printf '%s\n' "${out}" | grep -qF 'aaa111'; then
        pass "generated section still added"
    else
        fail "generated section still added" "${out}"
    fi
}

#-------------------------------------------------------------------------------
# Test 5: anchor fallbacks — footer rule, then append.
#-------------------------------------------------------------------------------
test_anchor_fallbacks() {
    echo "TEST: falls back to the footer rule, then to appending"

    local body out
    body="$(mktemp)"
    trap "rm -f '${body}'" RETURN

    cat > "${body}" <<'EOF'
## Summary

No checklist in this one.

---

Generated by `/team-pickup` at 2026-08-02T10:00:00Z
EOF
    out="$(printf '%s\n' "${SHOTS_ONE}" | bash "${INJECT}" "${body}")"

    local shot_line footer_line
    shot_line="$(printf '%s\n' "${out}" | grep -n '^## Screenshots$' | cut -d: -f1)"
    footer_line="$(printf '%s\n' "${out}" | grep -n 'Generated by' | cut -d: -f1)"
    if [ -n "${shot_line}" ] && [ "${shot_line}" -lt "${footer_line}" ]; then
        pass "section lands above the generated-by footer"
    else
        fail "section lands above the generated-by footer" "${out}"
    fi

    printf 'Just a summary, nothing else.\n' > "${body}"
    out="$(printf '%s\n' "${SHOTS_ONE}" | bash "${INJECT}" "${body}")"
    if printf '%s\n' "${out}" | head -1 | grep -qF 'Just a summary' &&
        printf '%s\n' "${out}" | grep -qF '## Screenshots'; then
        pass "plain body → appended, original first line kept"
    else
        fail "plain body → appended, original first line kept" "${out}"
    fi
}

#-------------------------------------------------------------------------------
# Test 6: the rest of the body survives verbatim (checklist state included).
#-------------------------------------------------------------------------------
test_body_preserved() {
    echo "TEST: the rest of the body — ticked boxes included — survives verbatim"

    local body out
    body="$(mktemp)"
    trap "rm -f '${body}'" RETURN
    write_body "${body}"

    out="$(printf '%s\n' "${SHOTS_TWO}" | bash "${INJECT}" "${body}")"

    local line missing=0
    while IFS= read -r line; do
        [ -n "${line}" ] || continue
        printf '%s\n' "${out}" | grep -qF -- "${line}" || { missing=$((missing + 1)); echo "    lost: ${line}"; }
    done < "${body}"

    if [ "${missing}" -eq 0 ]; then
        pass "every original non-blank line still present"
    else
        fail "every original non-blank line still present" "${missing} lost"
    fi

    if printf '%s\n' "${out}" | grep -qF -- '- [x] Toggle persists across reload' &&
        printf '%s\n' "${out}" | grep -qF -- '- [ ] Settings page renders the Carbon light palette'; then
        pass "checkbox states untouched"
    else
        fail "checkbox states untouched"
    fi
}

#-------------------------------------------------------------------------------
# Test 7: usage errors.
#-------------------------------------------------------------------------------
test_usage() {
    echo "TEST: usage errors exit 2"

    local rc
    printf '' | bash "${INJECT}" >/dev/null 2>&1
    rc=$?
    if [ "${rc}" -eq 2 ]; then
        pass "missing body file exits 2"
    else
        fail "missing body file exits 2" "exit ${rc}"
    fi

    printf '' | bash "${INJECT}" /nonexistent/body.md >/dev/null 2>&1
    rc=$?
    if [ "${rc}" -eq 2 ]; then
        pass "unreadable body file exits 2"
    else
        fail "unreadable body file exits 2" "exit ${rc}"
    fi
}

echo "=== inject-screenshots.sh tests ==="
test_inserts_before_checklist
test_idempotent_replace
test_empty_input_is_noop
test_human_section_untouched
test_anchor_fallbacks
test_body_preserved
test_usage

echo
echo "=== ${TESTS_RUN} tests, ${TESTS_FAILED} failed ==="
if [ "${TESTS_FAILED}" -gt 0 ]; then
    printf '  - %s\n' "${FAILED_NAMES[@]}"
    exit 1
fi
exit 0
