---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
