#!/bin/bash
# ralph-pr.sh - Open a PR summarizing all Ralph-completed issues
# Usage: ./scripts/ralph/ralph-pr.sh <prd-issue-number> [base-branch]
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

PRD_NUMBER="${1:-}"
BASE_BRANCH="${2:-master}"

if [ -z "$PRD_NUMBER" ]; then
  echo "Usage: $0 <prd-issue-number> [base-branch]"
  echo ""
  echo "  prd-issue-number  The parent PRD issue number"
  echo "  base-branch       Branch to merge into (default: master)"
  echo ""
  echo "Example: $0 42"
  exit 1
fi

BRANCH_NAME=$(git branch --show-current)
PRD_TITLE=$(gh issue view "$PRD_NUMBER" --json title --jq '.title')

echo "=== Ralph PR ==="
echo "PRD #${PRD_NUMBER}: ${PRD_TITLE}"
echo "Branch: ${BRANCH_NAME} → ${BASE_BRANCH}"
echo ""

# Gather closed issues with ralph:done label
DONE_ISSUES=$(gh issue list --label "ralph:done" --state closed --json number,title --limit 50 \
  | jq -r '.[] | "- Closes #\(.number): \(.title)"')

if [ -z "$DONE_ISSUES" ]; then
  echo "No completed Ralph issues found. Nothing to create a PR for."
  exit 1
fi

echo "Completed issues:"
echo "$DONE_ISSUES"
echo ""

# Push current branch if needed
if ! git ls-remote --exit-code --heads origin "$BRANCH_NAME" &>/dev/null; then
  echo "Pushing branch to remote..."
  git push -u origin "$BRANCH_NAME"
fi

# Create PR
PR_URL=$(gh pr create \
  --base "$BASE_BRANCH" \
  --head "$BRANCH_NAME" \
  --title "feat: ${PRD_TITLE}" \
  --body "$(cat <<EOF
## Summary

Implementation of PRD #${PRD_NUMBER}: ${PRD_TITLE}

## Completed Issues

${DONE_ISSUES}

## Implementation Notes

See individual issue comments for per-issue implementation details.

## Test plan

- [ ] All app-level tests pass (\`cd apps/<app> && npm test\`)
- [ ] Lint passes (\`npm run lint\`)
- [ ] Format check passes (\`npm run format:check\`)
- [ ] Coverage thresholds met (CI will verify)

---
Generated by [Ralph Loop](scripts/ralph/USAGE.md)
EOF
)")

echo ""
echo "PR created: $PR_URL"
