# This is a basic workflow to help you get started with Actions

name: deploy cloud app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted-cloud

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: sudo chmod -R 777 ./

      - name: Git Checkout
          uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.15'

      - name: Use npm 8
        run: npm i -g npm@8

      - name: NPM Bootstrap
        if: steps.is-affected.conclusion == 'success'
        run: npm run bootstrap
      
      - name: frontend build
        run: npm run build --prefix apps/frontend

      - name: Docker Build Frontend Code Container
        run: |
          docker build \
          -f apps/frontend/Dockerfile \
          -t frontend \
          .


      # - name: docker compose down
      #   run: sudo docker-compose down

      # - name: docker build
      #   run: docker-compose build

      # - name: docker compose up
      #   run: sudo docker-compose up -d --force-recreate 
 
      