# This is a basic workflow to help you get started with Actions

name: Build and Publish Cloud

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: sudo chmod -R 777 ./

      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.15'

      - name: Use npm 8
        run: npm i -g npm@8

      - name: NPM Bootstrap
        run: npm run bootstrap

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: frontend build
        run: npm run build --prefix apps/frontend

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64
          context: .
          file: apps/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart_smoker:frontend
      

      - name: Build and push Backend
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64
          context: .
          file: apps/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart_smoker:backend 



  Deploy:
      needs: build
      uses: benjr70/Smart-Smoker-V2/.github/workflows/deploy.yml@master 